leanprover/vscode-lean4

- src/input.ts
I'm guessing this was an oversight 😄
> input.ts: replace lean.input with lean4.input

- src/extension.ts
- src/leanclient.ts
THIS BREAKS THE LEAN 3 EXTENSION (probably).
> Only send didOpen for visible text documents.

- vscode-lean4/src/abbreviation/rewriter/AbbreviationRewriter.ts
fix: add logging to abreviation rewriter so we can catch any future flakiness
I create a new output channel named "Lean: Editor" which can be shared if we have any other future places we want to be able to write errors from the client.  This complements "Lean: Server" where we show anything that goes wrong with launching the server.
> add logging to abreviation rewriter so we can catch any future flakiness

- lean4-infoview/src/infoview/rpcSessions.tsx
I think this explains some of the debug output we see after editing lean files for a while.
> This fixes a leak in cleaning up RpcSessions objects

- vscode-lean4/src/infoview.ts
- vscode-lean4/src/leanclient.ts
An alternative approach to #66 which restarts the whole infoview.
> fix: subscription counting and client running check

- README.md
doc: fix readme to remove unnecessary instructions and fix some typos.
> Fix readme to remove unnecessary instructions and fix some typos.

- vscode-lean4/src/utils/leanInstaller.ts
> fix: use progress notification instead of OutputChannel for lean installation

- lean4-infoview/src/lspTypes.ts
- vscode-lean4/media/progress-error-dark.svg
- vscode-lean4/media/progress-error-light.svg
- vscode-lean4/src/taskgutter.ts
Depends on https://github.com/leanprover/lean4/pull/845, but also works (for me) with the current version of the server (the bar will still be yellow in that case).
closes #67
> Make progress bar red when processing stopped with an error

- vscode-lean4/src/leanclient.ts
- vscode-lean4/src/taskgutter.ts
- vscode-lean4/src/utils/leanpkg.ts
> fix: support for running lean server on 'untitiled' files.

- vscode-lean4/package-lock.json
- vscode-lean4/src/infoview.ts
> fix: copyToComment sometimes fails to do anything.

- lean4-infoview/src/infoview/index.css
- lean4-infoview/src/infoview/tooltips.tsx
Nothing major, just making the colors a bit more subdued, rounding some corners, etc.
I'm still unhappy about the general styling of the infoview, there's lots of unstructured headers.  I'm often losing the overview of what's going on, in particular if there's multiple pins.
> Some CSS tweaks.

- vscode-lean4/package.json
Looking at https://github.com/leanprover/lean4/blob/master/doc/images/code-ext.png, I realized that the displayed part of the description couldn't be less helpful...
> Revise description.

- .github/workflows/on-push.yml
- package-lock.json
- vscode-lean4/package-lock.json
- vscode-lean4/package.json
- vscode-lean4/src/infoview.ts
- vscode-lean4/src/leanclient.ts
This PR contains (related with #114).
- Update vscode-languageclient version from 7.0.0. to 8.0.0-next.14 (language client newest version).
PR #159 needs to merge this current PR (#162) first to get the complete solution working.
> Update vscode-languageclient version

- CHANGELOG.md
- README.md
- lean4-infoview-api/package-lock.json
- lean4-infoview-api/src/infoviewApi.ts
- lean4-infoview/src/infoview/goalCompat.ts
- lean4-infoview/src/infoview/goals.tsx
- lean4-infoview/src/infoview/index.css
- lean4-infoview/src/infoview/info.tsx
- lean4-infoview/src/infoview/rpcInterface.ts
- lean4-infoview/src/infoview/traceExplorer.tsx
- vscode-lean4/package-lock.json
- vscode-lean4/package.json
- vscode-lean4/src/config.ts
- vscode-lean4/src/infoview.ts
Part II of issue https://github.com/leanprover/vscode-lean4/issues/76  is adding filter buttons for hiding hypotheses that have either isType or isInstance set to true.  
https://user-images.githubusercontent.com/18707114/169914051-a802e4b9-5fa4-4fc6-9d7c-34ed6af91517.mp4
> Add type and instance filters for hypotheses

- vscode-lean4/test/suite/info/info.test.ts
- vscode-lean4/test/suite/utils/helpers.ts
This adds some interesting edits that modify the pinned position.
> fix: add more pinning tests.

- .github/workflows/on-push.yml
- vscode-lean4/src/utils/clientProvider.ts
- vscode-lean4/src/utils/leanInstaller.ts
- vscode-lean4/test/suite/runTest.ts
This should fix the test problem.
> fix: startup ordering, cannot block on showInstallOptions or installElan

- lean4-infoview/src/infoview/traceExplorer.tsx
A marginal improvement that makes it clear that the trace is just loading and not broken.
> feat: show loading message in trace explorer

- vscode-lean4/src/utils/batch.ts
> fix: issue 232: extension should work with hard coded lake path in the lean4/lakePath setting

- vscode-lean4/package.json
- vscode-lean4/src/infoview.ts
- vscode-lean4/src/utils/clientProvider.ts
Fixes https://github.com/leanprover/vscode-lean4/issues/235
> fix: Stop reporting RpcErrorCode.WorkerExited

- .eslintrc.js
- lean4-infoview-api/src/rpcApi.ts
- lean4-infoview/src/infoview/goals.tsx
- lean4-infoview/src/infoview/index.css
- lean4-infoview/src/infoview/traceExplorer.tsx
Companion PR to https://github.com/leanprover/lean4/pull/1448
> feat: trace nodes with messages

- .vscode/launch.json
- vscode-lean4/package-lock.json
- vscode-lean4/src/config.ts
- vscode-lean4/src/utils/clientProvider.ts
- vscode-lean4/src/utils/leanInstaller.ts
- vscode-lean4/test/suite/bootstrap/bootstrap.test.ts
- vscode-lean4/test/suite/docview/docview.test.ts
- vscode-lean4/test/suite/index/index.ts
- vscode-lean4/test/suite/pre-bootstrap/user.test.ts
- vscode-lean4/test/suite/runTest.ts
- vscode-lean4/test/suite/toolchains/toolchain.test.ts
- vscode-lean4/test/suite/utils/helpers.ts
Slipped through the tests unfortunately, because the tests don't test a totally clean machine and the popup experience so I added a new pre-bootstrap test for this.
Fixes #265
> fix: boostrap on clean machine was broken.

- README.md
> fix: error in installation instructions

- lean4-infoview/src/infoview/goals.tsx
- lean4-infoview/src/infoview/index.css
- lean4-infoview/src/infoview/info.tsx
- vscode-lean4/package-lock.json
Fixes #285
This is my naive attempt at fixing one of the issues with the current InfoView, but I'm ready to do it differently if this is not suitable.
> Bring back goals count in tactic state.

- lean4-infoview-api/package-lock.json
- lean4-infoview-api/src/infoviewApi.ts
- lean4-infoview/package-lock.json
- lean4-infoview/src/infoview/goalLocation.tsx
- lean4-infoview/src/infoview/goals.tsx
- lean4-infoview/src/infoview/info.tsx
- lean4-infoview/src/infoview/messages.tsx
- lean4-infoview/src/infoview/tooltips.tsx
- lean4-infoview/src/infoview/util.ts
- package-lock.json
- vscode-lean4/package-lock.json
- vscode-lean4/package.json
- vscode-lean4/src/config.ts
- vscode-lean4/src/infoview.ts
> Hover setting

- vscode-lean4/package-lock.json
- vscode-lean4/package.json
Hopefully the last PR of this kind.
> Update packaging tooling versions

- vscode-lean4/package.json
This came up [on Zulip](https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/normalising.20whitespace/near/397407427).
> Change whitespace default settings

- vscode-lean4/src/utils/clientProvider.ts
This was accidentally introduced in the previous PR #347.
> Remove bootstrap error message

- vscode-lean4/src/projectinit.ts
When creating a new standalone project, clicking on either `Main.lean` or the root of the library will yield a "Rebuild Imports" message. This is somewhat annoying, so we now immediately build once after initializing the project.
> Build Lean project after initialization

- vscode-lean4/package.json
- vscode-lean4/syntaxes/lean4-markdown.json
- vscode-lean4/syntaxes/lean4.json
This was creating problems for Linguist: https://github.com/github-linguist/linguist/pull/6616/files#r1401634263
> Use `lean4` scope for lean-markdown

- vscode-lean4/media/guide-installDeps-linux.md
- vscode-lean4/media/guide-installDeps-mac.md
- vscode-lean4/media/guide-installDeps-windows.md
> doc: move description of dependencies to the front

- vscode-lean4/src/abbreviation/rewriter/AbbreviationRewriter.ts
At https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/vscode.20cursor.20position.20bug, it was reported that the new abbreviation provider cursor handling (#389) consistently produced incorrect behavior with VSCodeVim being installed.
This PR makes the abbreviation handling fall back to the old behavior when the Vim extension is installed.
> fix: use manual cursor manipulation when vim extension is installed

- vscode-lean4/package-lock.json
- vscode-lean4/src/projectinit.ts
This bug was introduced by #407.
> fix: broken create project command

- vscode-lean4/src/leanclient.ts
- vscode-lean4/src/utils/leanpkg.ts
To be merged after leanprover/lean4#3298.
> feat: lakefile.toml support

- vscode-lean4/src/leanclient.ts
This came up at https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/Lean.20fail.20to.20start.20for.20an.20unknown.20reason/near/430465800.
Older Lean 4 versions do not show the stale dependency diagnostic under "Messages" because the `fullRange` span was wrong. This re-adds the stale dependency notifications for those versions.
> chore: re-add stale dependency notifications for older lean4 versions

- vscode-lean4/src/leanclient.ts
> Fix incorrect string formatting

- vscode-lean4/loogleview/index.ts
- vscode-lean4/src/extension.ts
- vscode-lean4/src/loogleview.ts
This PR adds the VS Code and Lean 4 extension versions to the Loogle user agent.
> feat: loogle user-agent with versions

- vscode-lean4/src/extension.ts
It was possible for the extension to attempt to activate the Lean 4 features twice, which would result in failure during the second activation. This PR fixes that race condition.
This bug was probably what caused https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/VScode.20extension.20error/near/446135693.
> fix: potential activation race condition

- vscode-lean4/manual/manual.md
- vscode-lean4/package.json
- vscode-lean4/src/projectoperations.ts
- vscode-lean4/src/utils/exturi.ts
- vscode-lean4/src/utils/fsHelper.ts
- vscode-lean4/src/utils/lake.ts
- vscode-lean4/src/utils/manifest.ts
This PR adds a new 'Project: Fetch Mathlib Build Cache For Focused File' command for use in Mathlib itself.
Closes #416.
> feat: fetch mathlib build cache for focused file command

- vscode-lean4/src/projectinit.ts
> fix: initial commit not working on fresh Git install

- lean4-unicode-input/src/abbreviations.json
> chore: remove rial symbol

- vscode-lean4/src/projectinit.ts
This PR re-uses the search bar of the quick pick dialog in the "Download Project" UI for entering URLs.
Closes #530.
> feat: improve 'Download Project' UI

- vscode-lean4/.vscodeignore
> fix: add another missing file to bundle

- vscode-lean4/src/taskgutter.ts
This PR improves the performance of the new editor decorations that were introduced in #585.
Specifically, it makes the following adjustments:
- The result of `workspace.getConfiguration` is cached. This VS Code API is slower than expected, so we can't call it for every single decoration.
- The decoration debounce delay is increased.
- The decoration debounce delay applies to 'unsolved goals' decorations as well.
- The work to compute the decorations is slightly reduced.
> feat: improve decoration computation performance

- vscode-lean4/src/utils/elan.ts
- vscode-lean4/src/utils/elanCommands.ts
- vscode-lean4/src/utils/manifest.ts
- vscode-lean4/src/utils/semverRegex.ts
This PR ensures that the installed toolchains in all commands that display them are sorted in a sensible manner.
> feat: sorted installed toolchains
