- package.json
- src/extension.ts
Adds a command to restart the server. It seems to work, but I don't know any Typescript. In particular I'm assuming closures referencing `client` will always see its new version, which they do seem to?
> Command to restart the whole server

- syntaxes/lean4.json
> Syntax highlighting for `noncomputable` and definition names.

- package-lock.json
- src/config.ts
- src/extension.ts
- src/leanclient.ts
The initial version check is done before adding the path variables specified in the user's config file, so if the user is counting on that to set the lean path, the version check will always fail. `exec` defaults to `/bin/sh`, so if that's not your login shell, the vscode config is kind of the only way to do it. Alternatively, the extension could use SHELL to figure out what shell is actually being used and pass that to exec.
```
const user_shell = process.env.SHELL
...
const { stdout, stderr } = await promisify(exec)(cmd, {cwd: folderPath, shell: user_shell })
```
I took the code to update the process path from `leanclient.ts`, but I think `paths.join(path.delimiter) + path.delimiter + process.env.Path` needs to be broken up into either `process.env.Path` (for windows) and …
> add user paths for version check, fix path field access

- package.json
- src/config.ts
- src/leanclient.ts
Users may set how long they wish the server to wait after the last edit before starting elaboration. See also Zulip [thread](https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/Has.20Lean.204.20gotten.20slower.3F).
> Expose configurable elaboration delay

- README.md
This PR adds a changelog to the README. I regret not starting one when I transferred the repo to leanprover-community, so I reconstructed a full change log now. @Kha also mentioned to me that it would be helpful to keep the pinned Nix version up to date. The PR also updates the functionality section in the README.
For two changes I couldn't figure out what it is they did without further context. I've marked those with `(?)` to indicate that they still need an understandable description.
> Adding a changelog

- vscode-lean4/.vscodeignore
- vscode-lean4/package-lock.json
- vscode-lean4/package.json
We were missing some extra configuration in the `.vsix` package which broke language features as reported on [Zulip](https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/ctrl-.2F.20.22toggle.20comment.22.20broken.20in.20vscode-lean4.200.2E0.2E32). Also pins a newer version of VSCE which [unbreaks](https://github.com/microsoft/vscode-vsce/commit/599cea7eb50ef43548c253633fd3dbabd4289c87) the `.vscodeignore` behaviour.
> fix: packaging

- vscode-lean4/package.json
- vscode-lean4/src/config.ts
- vscode-lean4/src/leanclient.ts
Users may wish to provide additional arguments to the Lean 4 server. For example, to add plugins or set other configuration options (ex. timeout), This PR adds a `serverArgs` setting to allow users to do just that.
> feat: add setting to configure server arguments

- vscode-lean4/src/docview.ts
- vscode-lean4/src/extension.ts
Like this:
And still available here:
both work and fixed a bug so the "back/forward" stack also works.
> fix: move "show all abbreviations" command to docview.ts and make it more discoverable

- lean4-infoview/src/infoview/rpcSessions.tsx
- lean4-infoview/src/infoviewApi.ts
- lean4-infoview/src/lspTypes.ts
- vscode-lean4/src/infoview.ts
Fixes #73.
It also allows us to explicitly close sessions in the future instead of / in addition to the keep-alive system.
> Send RPC keep-alive from extension instead of infoview.

- vscode-lean4/src/utils/leanInstaller.ts
zsh's `read` does not support some of the given flags, and I don't even want to think about fish
> Make elan install compatible with other Linux shells

- vscode-lean4/src/leanclient.ts
- vscode-lean4/src/utils/leanpkg.ts
It happens when you deliberately crash the lean client multiple times by requesting invalid versions.
The fix is easy, make LanguageClient use the one OutputChannel that our extension creates instead of having it create another one.
> fix: multiple output channels named "Lean4" are showing up 

- package.json
on windows we need to use double quotes for command line arguments.
> Fix the eslint command line so it works on Windows.

- vscode-lean4/package.json
This allows editor selection expansion (for example when double-clicking a word) to respect custom parentheses used in Lean. The new value for the setting is based on the `wordPattern` property in `language-configuration.json`. For comparison, the default value of the setting is `` `~!@#$%^&*()-=+[{]}\\|;:'\",.<>/?``.
An issue with the previous behavior was, for example, when double-clicking `b` in `⟨a, b⟩`, `b⟩` was selected instead of just `b` (as mentioned in https://github.com/leanprover/lean4/issues/767).
> Add configuration default for `editor.wordSeparators`

- vscode-lean4/src/infoview.ts
fixes #71 
A simple window.showTextDocument does the trick.
> fix: reveal file location should move the keyboard focus to the text editor

- lean4-infoview/src/infoview/messages.tsx
Minor cleanup of console.log errors.  Do we want to implement a retry in the lazy fetch of updated diagnostics or just wait for the next edit?
> fix: some more -32801 errors are reported in the console log.

- vscode-lean4/src/extension.ts
- vscode-lean4/src/infoview.ts
- vscode-lean4/src/leanclient.ts
- vscode-lean4/src/taskgutter.ts
- vscode-lean4/src/utils/clientProvider.ts
- vscode-lean4/src/utils/leanInstaller.ts
- vscode-lean4/src/utils/leanpkg.ts
- vscode-lean4/src/utils/projectInfo.ts
Fixes #115
Turns out the work to support "untitled" files broke the "ad hoc" files.   Now I've tested the following scenarios:
- start vs code from start menu (not from a folder), File/Open file..., works (let's call this an "adhoc" file).
- start vs code from start menu (not from a folder), File/New file, set Lean4... works (let's call this an "untitled" file).
- start vs code from folder, open files in that folder, works!
- now File/Open file... from somewhere else, also works!
- now File/New file & set Lean4, also works!  
This last option now has 3 LeanClients running, one for the folder, and one for the adhoc package root, and one for 'untitled' files.  
For "adhoc" files the extension searches upwards in the directory hierarchy for a Lean package root and creates a new LeanClient …
> fix: #115 : Infoview not working for external file

- vscode-lean4/src/leanclient.ts
- vscode-lean4/src/utils/clientProvider.ts
- vscode-lean4/src/utils/leanInstaller.ts
fix: newly restarted client also needs to get DidOpenTextDocumentNotifications for existing open docs otherwise the lean server raises this error and crashes on the next edit to the open file.
```
Watchdog error: cannot find open document 'file:///d%3A/Temp/lean_examples/Foo/Main.lean'
[Info  - 8:57:59 PM] Connection to server got closed. Server will restart.
```
> fix: select toolchain was broken!

- README.md
- vscode-lean4/package.json
- vscode-lean4/src/config.ts
- vscode-lean4/src/extension.ts
- vscode-lean4/src/infoview.ts
- vscode-lean4/src/leanclient.ts
- vscode-lean4/src/utils/batch.ts
- vscode-lean4/src/utils/clientProvider.ts
- vscode-lean4/src/utils/leanInstaller.ts
- vscode-lean4/src/utils/leanpkg.ts
- vscode-lean4/src/utils/projectInfo.ts
See [Zulip Discussion](https://leanprover.zulipchat.com/#narrow/stream/147302-lean4-dev/topic/Expose.20--load-dynlib.20to.20Lean.3F)
This PR is dependent on #117 
Proposal, replace the following setting:
With:
Then the rules for using `lake serve` would be:
1. is 'lake' or 'lake.exe' found in the toolchainPath, If not don't use `lake`
2. is there a `lakefile.lean` in the current workspace root?  If not don't use `lake`
3. If the above are both good, use `lake serve` with optional +version if there's a workspace override in effect.
4. If `lake serve` fails fall back on `lean --server`.
This PR also fixes a bug introduced by support for "multi-workspace" namely that the "currentVersion" maintained in LeanpkgService needs to be "per-workspace".
> feat: use lake serve, take 2

- .eslintrc.js
- vscode-lean4/src/config.ts
- vscode-lean4/src/docview.ts
- vscode-lean4/src/extension.ts
- vscode-lean4/src/infoview.ts
- vscode-lean4/src/leanclient.ts
- vscode-lean4/src/taskgutter.ts
- vscode-lean4/src/utils/batch.ts
- vscode-lean4/src/utils/clientProvider.ts
- vscode-lean4/src/utils/leanInstaller.ts
- vscode-lean4/src/utils/leanpkg.ts
- vscode-lean4/src/utils/localStorage.ts
- vscode-lean4/src/utils/projectInfo.ts
- vscode-lean4/src/utils/tempFolder.ts
- vscode-lean4/tsconfig.json
and not iterable exceptions in the results from findLeanPackageRoot and findLeanPackageVersionInfo.  I also turned on strictNullChecks and noImplicitAny compilerOptions which revealed & fixed a few more potential bugs.
I tested the following "open file/open folder" scenarios:
1. open random mathlib file (D:\git\leanprover\mathlib4\Mathlib\Data\Array\Basic.lean) and not open folder.  It installs the mathlib version of lean (currently leanprover/lean4:nightly-2022-01-23) and works.
1. Goto definition from mathlib to Array.push jumps to (C:\users\clovett\.elan\toolchains\leanprover--lean4---nightly-2022-01-23\lib\lean\src\init\prelude.lean) and creates a new LeanClient in (c:\users\clovett\.elan\toolchains\leanprover--lean4---nightly-2022-01-23").
1. Open folder of a local lake package …
> fix: adhoc and untitled files were hitting some null reference exceptions

- vscode-lean4/package.json
Prevents remote machine settings from inheriting paths set up for the local machine. I also include `lean4.serverEnv` because that contains `LEAN_SRC_PATH` and possibly `LEAN_PATH`.
> feat: tag path settings as machine-specific

- .gitignore
- README.md
- vscode-lean4/package.json
- vscode-lean4/src/leanclient.ts
- vscode-lean4/src/utils/clientProvider.ts
- vscode-lean4/src/utils/leanInstaller.ts
- vscode-lean4/src/utils/projectInfo.ts
1. add optimization that skips the lake test on well known versions because it is too slow where the optimization is based on well known lean-toolchain version strings.  
1. Cache `lean --version` check results because we were doing 2 checks on each reload.
I put a console output that measures full lean server "restart" time following a `Select Toolchain` choice, so I can run release bits to get good measurements, and with this PR it is:
| Version      | Full restart time| Lake? |
| ----------- | ----------- | -------------|
| leanprover/lean4:nightly-2022-02-01| 658 ms | no |
| leanprover/lean4:nightly-2022-02-16 | 823 ms | yes |
| leanprover/lean4:4.0.0-m3 | 656 ms | no |
Previously without this PR the times are:
| Version      | Full restart time | Lake? |
| ----------- | ----------- …
> fix: improve startup performance of LeanClient

- README.md
- vscode-lean4/package-lock.json
- vscode-lean4/src/leanclient.ts
- vscode-lean4/src/utils/clientProvider.ts
- vscode-lean4/test/suite/multi/multi.test.ts
- vscode-lean4/test/suite/simple/simple.test.ts
- vscode-lean4/test/suite/toolchains/toolchain.test.ts
- vscode-lean4/test/suite/utils/helpers.ts
fix: sometimes depending on how we get to this function the Uri has different case on some folders, like I see "d:\temp\..." or "d:\Temp\..." and that caused this function to fail to see the file was in the same workspace and then it failed to create a new `lean --worker` at all for that file.  This was causing some test flakiness on Windows machines.
Also found and fixed some other obvious bugs in the tests and test utils.
> fix flakey test

- .eslintrc.js
- .vscode/settings.json
This PR fixes the issue with eslint with tsconfig.json adding missing directories in eslint.workingDirectories inside .vscode/settings.json
> [issue 146] Spurious error from eslint extension

- .eslintrc.js
- .vscode/settings.json
(Regarding first commit.) I semi-frequently inspect the actual build artifacts and imported libraries, so it is more useful to me to keep them visible. They would still be excluded from search results with this change. I think you introduced some of these @gebner , are you okay with this change?
The other commits hopefully fix the ESLint setup.
> Development config fixes

- vscode-lean4/src/utils/leanInstaller.ts
Sebastian wanted me to change `elan-init.ps1` command line args to be more consitent with elan-init.exe.
See related elan PR https://github.com/leanprover/elan/pull/65
> fix: switch to new consistent elan-init.ps1 arguments.

- vscode-lean4/src/utils/leanInstaller.ts
`||` and `&&` have the same precedence in bash
> fix: elan installation on Unix

- .vscode/launch.json
- vscode-lean4/src/leanclient.ts
Some timing conditions can happen while running unit tests that cause the LanguageClient stop method to throw an exception which then causes those tests to fail.  We really don't care if stop fails, so I added a try/catch and this seems to help make the tests less flakey.
Note the first workflow run failed, but that is with an unrealted error: `Failed to get VS Code archive location`.
> found a fix for flakey tests

- lean4-infoview/src/infoview/info.tsx
- lean4-infoview/src/infoview/interactiveCode.tsx
- lean4-infoview/src/infoview/rpcInterface.ts
- lean4-infoview/src/infoview/tooltips.tsx
- vscode-lean4/src/infoview.ts
- vscode-lean4/src/leanclient.ts
- vscode-lean4/src/utils/converters.ts
- Add go-to-definition to the infoview with a ctrl+click UI mimicking VSCode.
https://user-images.githubusercontent.com/13901751/169145205-15d6cfe8-8fa6-422e-ba51-e1ed36fcf756.mp4
- Add `subexprPos` to `CodeToken` to know subexpression positions for visual tactics like interactive `rw` and `conv`.
- ~~Put RPC calls in a namespace and remove inconsistent namespace prefixes.~~
This needs a server PR (leanprover/lean4#1157).
> feat: add go-to-definition to infoview

- lean4-infoview/src/infoview/interactiveCode.tsx
- lean4-infoview/src/infoview/tooltips.tsx
On Mac, meta-click rather than ctrl-click seems to be the default for go-to-definition.
> feat: support go-to-def on MacOS

- README.md
Can't embed the video unfortunately, it doesn't work on 
https://github.com/leanprover/vscode-lean4/tree/clovett/video
but it does work in 
https://github.dev/leanprover/vscode-lean4/tree/clovett/video
so it has to be a link that jumps the user out to YouTube.
> doc: add quickstart video to readme

- lean4-infoview-api/src/lspTypes.ts
- lean4-infoview/src/components.ts
- lean4-infoview/src/components.tsx
- lean4-infoview/src/infoview/editorConnection.ts
- lean4-infoview/src/infoview/errors.tsx
- lean4-infoview/src/infoview/goalCompat.ts
- lean4-infoview/src/infoview/goals.tsx
- lean4-infoview/src/infoview/info.tsx
- lean4-infoview/src/infoview/interactiveCode.tsx
- lean4-infoview/src/infoview/rpcInterface.ts
- lean4-infoview/src/infoview/rpcSessions.tsx
- lean4-infoview/src/infoview/traceExplorer.tsx
- lean4-infoview/src/infoview/util.ts
- vscode-lean4/src/infoview.ts
This is a set of refactors that me and @vtec234 made while working on user widgets and context suggestions.
- some docstrings
- refactor InteractiveHypothesis => InteractiveHypothesisBundle
- refactor: extract HypothesisBundle render to own component.
- introduce a `useAsync` hook for use with rpcs
- refactor TypePopupContents
- InteractiveGoal and InteractiveHypothesisBundle have mvarId? and fvarIds? fields
- helper function mapRpcError
- helper enum RpcErrorCode
- new override of useEventResult
- fix a bug in handleInsertText where it was doing reference eq instead of string eq.
Co-authored-by: @Vtec234
> refactor: preparing for user-widgets and context suggestions

- lean4-infoview/src/infoview/infos.tsx
- lean4-infoview/src/infoview/main.tsx
When we close a Lean file, the cursor position temporarily becomes `undefined` and clears all pins. This is fixed here by keeping the `Infos` component alive for as long as the server is running and adapting it to handle the `undefined` case.
> feat: preserve pins when cursor position is undefined

- README.md
- vscode-lean4/package.json
- vscode-lean4/src/config.ts
- vscode-lean4/src/leanclient.ts
This is a very selfish addition, but one I desperately need in order to test `lake serve` without needing to setup a custom Lean toolchain on every rebuild.
> Add setting to specify the path to the Lake executable

- lean4-infoview/package-lock.json
- lean4-infoview/package.json
- lean4-infoview/src/infoview/index.css
- lean4-infoview/src/infoview/interactiveCode.tsx
- lean4-infoview/src/infoview/tooltips.tsx
Beginnings of a markdown rendering for infoview.
Related work items:
- [popup scrolling](https://github.com/leanprover/vscode-lean4/issues/210)
- [code block formatting](https://github.com/leanprover/vscode-lean4/issues/211)
- [Figure out if we want to do anything fun with hyperlinks in tooltips](https://github.com/leanprover/vscode-lean4/issues/212)
This version currently converts this
```lean
/--
This is a **cool** function, it can:
- slice bread
- make toast
- spread marmalade
- set a timer
Example usage:
let pt := { x : 1, y := 2 }
See code at [Foo.lean](http://github.com/leanprover/lean4).
-/
structure Point where
x : Float
y : Float
deriving Repr
```
We see this comparison, with editor hover widget on the left and the infoview hover widget on the right:
> feat: hook up markdown rendering in InfoView

- lean4-infoview/src/infoview/index.css
- lean4-infoview/src/infoview/interactiveCode.tsx
I noticed that markdown fonts look out of place on a high DPI screen. This is a quick fix for that which removes hardcoded font-sizes, so that we default to `--vscode-font-size` that the webview already puts on `body`.
> fix: font size in tooltips

- .github/workflows/on-push.yml
- .vscode/launch.json
- vscode-lean4/src/config.ts
- vscode-lean4/src/extension.ts
- vscode-lean4/src/utils/batch.ts
- vscode-lean4/src/utils/leanInstaller.ts
- vscode-lean4/test/suite/bootstrap/bootstrap.test.ts
- vscode-lean4/test/suite/index/index.ts
- vscode-lean4/test/suite/runTest.ts
- vscode-lean4/test/suite/simple/simple.test.ts
- vscode-lean4/test/suite/utils/helpers.ts
Fixes #216 
PowerShell by default has execution policy set to Restricted, meaning it will not run random powershell scripts.  This causes `elan-init.ps1` to fail during bootstrapping which is not ideal.  This fix temporarily changes the powershell execution policy to RemoteSigned so that the script can run, then restores the policy to what it was before after  `elan-init.ps1` completes.
This also fixes a recent regression that was causing: "waiting for lean server to start..." to happen in the case where the `lean` version check failed - it was caching the fact that it fails and didn't clear the cache after installing elan.
> fix: issue# 216 about powershell execution policy.

- vscode-lean4/src/config.ts
- vscode-lean4/src/extension.ts
- vscode-lean4/src/infoview.ts
- vscode-lean4/src/leanclient.ts
- vscode-lean4/src/utils/batch.ts
- vscode-lean4/src/utils/clientProvider.ts
- vscode-lean4/src/utils/leanInstaller.ts
- vscode-lean4/src/utils/logger.ts
- vscode-lean4/src/utils/projectInfo.ts
- vscode-lean4/test/suite/bootstrap/bootstrap.test.ts
- vscode-lean4/test/suite/docview/docview.test.ts
- vscode-lean4/test/suite/index/index.ts
- vscode-lean4/test/suite/info/info.test.ts
- vscode-lean4/test/suite/lean3/lean3.test.ts
- vscode-lean4/test/suite/multi/multi.test.ts
- vscode-lean4/test/suite/runTest.ts
- vscode-lean4/test/suite/simple/simple.test.ts
- vscode-lean4/test/suite/toolchains/toolchain.test.ts
- vscode-lean4/test/suite/utils/helpers.ts
- vscode-lean4/test/test-fixtures/multi/foo/lakefile.lean
- vscode-lean4/test/test-fixtures/multi/foo/lean-toolchain
- vscode-lean4/test/test-fixtures/multi/test/lakefile.lean
- vscode-lean4/test/test-fixtures/simple/lakefile.lean
This makes it easier to monitor relative performance and timeouts in our tests.
> test: Add timestamping on all console.log output.

- README.md
- vscode-lean4/package.json
- vscode-lean4/src/config.ts
- vscode-lean4/src/leanclient.ts
As discussed in [this Zulip thread](https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/VSCode.20Disable.20Output.20auto-focus/near/291145653), this PR makes the extension's behavior of automatically focusing the Output panel on new messages configurable by the user. I also defaulted the option to `false`, because as @Vtec234 [mentions](https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/VSCode.20Disable.20Output.20auto-focus/near/291236099), this feature is generally undesired and primarily useful when debugging the server (which should be rare).
> feat: configurable output autofocus

- vscode-lean4/src/utils/leanInstaller.ts
This fix adds a button to see the output (it redirects you to the output section inside VSCode)  to know the problem when restarting the server. Issue #181 
Before:
So I have two possible solutions:
1.- Show a button to activate output section inside VSCode (included in this PR)
2.- Automatically activate outputChannel (NOT included in this PR):
i.e.
By default, in Azure section:
But after detecting the failure (Going to Output section and displaying the error message): 
@Kha and @lovettchris let me know your thoughts.
*UPDATE: This PR contains 2nd solution.*
Final solution : 
After checking CR comments, the output message stays like this:
Based on: https://github.com/leanprover/vscode-lean4/pull/229
> fix: Failed to start language server: popup is too generic

- vscode-lean4/src/leanclient.ts
- vscode-lean4/src/utils/clientProvider.ts
- vscode-lean4/src/utils/leanInstaller.ts
> fix: adhoc files should not pick up default lean version from open folder

- vscode-lean4/src/leanclient.ts
After #229 panics were silently ignored when `autofocusOutput` is set to false, which is the default value.  This PR shows an error message box on stderr output if `autofocusOutput` is false.
> fix: show error message box for panics

- lean4-infoview/src/components.tsx
- lean4-infoview/src/infoview/interactiveCode.tsx
- lean4-infoview/src/infoview/traceExplorer.tsx
- lean4-infoview/src/infoview/userWidget.tsx
- lean4-infoview/src/infoview/util.ts
Extends `useAsync` with lazy loading.  It also fixes the nasty race condition with changing deps where the `useAsync` return value claimed to be fulfilled but was out-of-date.  E.g., this means that we use the props meant for a different widget, or send RPC objects to the wrong session.
> feat: useAsyncWithTrigger

- lean4-infoview/src/infoview/info.tsx
- lean4-infoview/src/infoview/messages.tsx
I found it pretty annoying that the different parts of the info update at different points in time:
1. First we show the dumb diagnostics from LSP.
2. Then the diagnostics are updated with the interactive ones.
3. Finally, the goal display is updated.
In the meantime, we've even got some slightly inconsistent display, where the three parts get out of sync.  More annoyingly though, it flickers a lot when you move the cursor through the file.
This PR changes the behavior so that all of the parts are updated at the same time.
> feat: atomic info updates

- lean4-infoview/src/infoview/goals.tsx
- lean4-infoview/src/infoview/index.css
As discussed in https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/De-emphasizing.20inaccessible.20hypothesis.20names
> feat: bring back inaccessible names highlighting

- lean4-infoview-api/src/infoviewApi.ts
- vscode-lean4/src/infoview.ts
The input is a `WorkspaceEdit` which empowers the infoview to be able to edit the document and workspace in any way.
> feat: add `applyEdit` to edit connection protocol

- lean4-infoview/src/infoview/info.tsx
- lean4-infoview/src/infoview/interactiveCode.tsx
- lean4-infoview/src/infoview/messages.tsx
I am working on a web version of Lean 4 and ran into the issue that some of the `useEffect` functions accidentally return a promise. The issue is described in some detail here: https://medium.com/geekculture/react-uncaught-typeerror-destroy-is-not-a-function-192738a6e79b. I am not sure why this is not an issue in the VSCode webview, but it is an issue in the browser.
> avoid returning promises in `useEffect`

- vscode-lean4/package-lock.json
- vscode-lean4/src/infoview.ts
- vscode-lean4/test/suite/bootstrap/bootstrap.test.ts
- vscode-lean4/test/suite/utils/helpers.ts
- vscode-lean4/test/test-fixtures/multi/foo/lean-toolchain
See [failure]( https://github.com/leanprover/vscode-lean4/actions/runs/3254321730/jobs/5346015206)
The `[LeanClient] running, started in 655 ms` means we reached the point where the LeanClient fires the `restarted` event, which is great, and even better the InfoView got that event and printed `[InfoProvider] got client restarted event`. The InfoView is supposed to call `clearRpcSessions` and `onClientRestarted`which calls `initInfoView` and that is supposed to trigger all the infoview updating.  But what if `if (client?.initializeResult) {` failed? then it would silently hang forever showing "Waiting for lean server to start".  We should change the test to print the contents of the infoview so we can confirm what is there. There is no race condition, the `this.running = true` is set to …
> test: add some logging to help debug random test failures.

- vscode-lean4/src/rpc.ts
It looks like we had a long-standing bug in the infoview RPC channel wherein method calls could start coming in from the other side before we get a chance to call `rpc.register`. This became much more observable when I messed with some other code but it's a potential source of some occurrences of the `Waiting for Lean server to start..` bug.
> fix: RPC race condition

- lean4-infoview/src/infoview/goals.tsx
At the moment, the Lean 4 VS Code extension reports "Goals accomplished 🎉" if the goal list is empty, as it did in Lean 3. 
However, far more often than in Lean 3, the phrase is an inappropriate descriptor of the situation.  For example:
````lean
example : True := by
exact h
````
With the cursor after `h`, one has two messages displayed, "Goals accomplished" and "unknown identifier 'h'".  (In Lean 3, there is no "Goals accomplished" message on this example.)
See [#1970](https://github.com/leanprover/lean4/issues/1970) for a full description of the issue and some proposed fixes -- I hope the Lean 4 devs will take this on!
In the short term, however, it seems worthwhile changing the message to something less confusing.  I propose here changing the message to "no goals".
Update: …
> Rename "goals accomplished" as "no goals"

- lean4-infoview-api/package-lock.json
- lean4-infoview-api/package.json
- lean4-infoview-api/src/rpcApi.ts
- lean4-infoview-api/src/rpcSessions.ts
- lean4-infoview-api/src/util.ts
- lean4-infoview/package-lock.json
- lean4-infoview/package.json
- lean4-infoview/src/index.tsx
- lean4-infoview/src/infoview/collapsing.tsx
- lean4-infoview/src/infoview/errors.tsx
- lean4-infoview/src/infoview/exprContext.tsx
- lean4-infoview/src/infoview/goalLocation.tsx
- lean4-infoview/src/infoview/goals.tsx
- lean4-infoview/src/infoview/index.css
- lean4-infoview/src/infoview/info.tsx
- lean4-infoview/src/infoview/interactiveCode.tsx
- lean4-infoview/src/infoview/messages.tsx
- lean4-infoview/src/infoview/tooltips.tsx
- lean4-infoview/src/infoview/traceExplorer.tsx
- lean4-infoview/src/infoview/userWidget.tsx
- lean4-infoview/src/infoview/util.ts
- package-lock.json
- vscode-lean4/package-lock.json
- vscode-lean4/package.json
There are many cases where we want to tell Lean which parts of the goal state are relevant to a particular action. For example, `simp [h₁, h₂]` marks these two hypotheses as the rewrite rules to use. This PR adds a mechanism to select one or more locations within the goal state. Below `h₁, h₂`, and the RHS of the goal type are selected.
This enables writing user widgets which use the current selection as a context/relevance filter for which parts of the goal to process. For example, the following widget ([source code](https://gist.github.com/Vtec234/2e0a6298887594f747cf364d8368b125)) becomes quite easily implementable:
https://user-images.githubusercontent.com/13901751/208323311-f084b07c-9ae7-4a64-acc2-d7463be97597.mp4
I believe that this also makes contextual suggestions …
> Multi-expression selection

- lean4-infoview/src/infoview/traceExplorer.tsx
I think this was just an oversight in the initial implementation, but posting it as a PR for visibility.
```lean
example : Nat → Nat :=
fun _ => _
--^ check out the error here
```
The error shows that we cannot fill in the placeholder `x✝: Nat ⊢ Nat`.  However we hide the `x✝` in goal embeds in the vscode extension.  It is shown just fine on the command-line and in neovim.
So to make it consistent with both the tactic state display and the other editors, this PR disables the hiding in this special case.
> fix: do not hide assumptions in goal embeds

- vscode-lean4/test/suite/simple/simple.test.ts
This test appears to fail often, e.g. in #300 and #291. This might be preferrable in any case as I am not sure the extension should care about where on disk the Lean toolchain is stored.
> ci: remove failing test

- README.md
- lean4-infoview-api/src/infoviewApi.ts
- lean4-infoview/src/infoview/collapsing.tsx
- lean4-infoview/src/infoview/goals.tsx
- lean4-infoview/src/infoview/index.css
- lean4-infoview/src/infoview/info.tsx
- lean4-infoview/src/infoview/messages.tsx
- lean4-infoview/src/infoview/traceExplorer.tsx
- vscode-lean4/package.json
- vscode-lean4/src/config.ts
- vscode-lean4/src/infoview.ts
This implements all suggestions from #299 to clarify the infoview display, especially in the presence of several goals.
---
This isn't yet fully working, I'll discuss the issue on Zulip.
> Infoview tweaks

- vscode-lean4/src/abbreviation/abbreviations.json
[`HImp.himp`](https://leanprover-community.github.io/mathlib4_docs/Mathlib/Order/Heyting/Basic.html#HImp)
> feat: shortcut for notation `HImp.himp`

- .eslintrc.js
- lean4-infoview/package-lock.json
- lean4-infoview/package.json
- lean4-infoview/rollup.config.js
- lean4-infoview/src/esm-shims/react-popper.ts
- lean4-infoview/src/infoview/goals.tsx
- lean4-infoview/src/infoview/index.css
- lean4-infoview/src/infoview/info.tsx
- lean4-infoview/src/infoview/infos.tsx
- lean4-infoview/src/infoview/interactiveCode.tsx
- lean4-infoview/src/infoview/messages.tsx
- lean4-infoview/src/infoview/rpcSessions.tsx
- lean4-infoview/src/infoview/tooltips.tsx
- lean4-infoview/src/infoview/traceExplorer.tsx
- lean4-infoview/src/infoview/util.ts
- lean4-infoview/src/loader.ts
- package-lock.json
- package.json
- vscode-lean4/src/infoview.ts
- vscode-lean4/webview/index.ts
This fix resolves #280, and #210.
- Replaced popper 2 with floating-ui.
- Update CSS for tooltip to allow for markdown comment scrolling when tooltip exceeds a certain height.
- Ensure tooltip stays within the infoview viewport by implementing custom flip logic as a floating-ui middleware. Tooltip position is based on pointer position instead of the size and position of the reference element - the element that is being hovered over. This allows for proper tooltip placement, regardless of the shape and size of the reference element. The default position of the tooltip is above and to the right of the pointer. The direction of the flip and the level of offset is based on the quadrant - within the viewport - in which the pointer was located when the hover event was triggered. Viewport …
> fix: Ensure large tooltip popups are not clipped and stay within the inforview viewport

- lean4-infoview/src/infoview/interactiveCode.tsx
Fixes #311. This is a stopgap that I didn't think through very much, but seems to work.
https://github.com/leanprover/vscode-lean4/assets/13901751/7228926d-1bb9-4c7b-81bb-52b1e25900ad
> feat: select subexpressions on contextmenu event

- vscode-lean4/package-lock.json
- vscode-lean4/src/docview.ts
```
- Update existing documentation links to point to `lean-lang.org`
- Add new doc links:
- Functional Programming in Lean
- The Mechanics of Proof
```
These links are from the [Lean docs](https://lean-lang.org/documentation/) website.
> Update Documentation View

- vscode-lean4/package.json
- vscode-lean4/src/config.ts
- vscode-lean4/src/leanclient.ts
This PR adds extension support for the `--no-build` flag when opening files so that dependencies are not automatically built anymore, overwriting existing oleans.
It rests on the corresponding backend change at leanprover/lean4#2665 and was originally motivated by https://github.com/leanprover/lean4/issues/2154#issuecomment-1655471667.
> Add opt-in dependency builds when opening files

- vscode-lean4/src/leanclient.ts
This PR adds a notification in the bottom right that is displayed when the server reports that the imports are out of date. It has a button that can be used to run the "Restart File" command in order to rebuild the imports.
> Notification for imports-out-of-date error

- vscode-lean4/package-lock.json
- vscode-lean4/src/extension.ts
- vscode-lean4/src/utils/clientProvider.ts
- vscode-lean4/test/suite/restarts/restarts.test.ts
- vscode-lean4/test/suite/toolchains/toolchain.test.ts
- vscode-lean4/test/suite/utils/helpers.ts
PR to play around with CI for a while to see if I can fix the tests.
> Assorted test fixes

- vscode-lean4/media/guide-setupProject.md
- vscode-lean4/package.json
- vscode-lean4/src/utils/clientProvider.ts
- vscode-lean4/test/suite/utils/helpers.ts
- Remove the server restart prompt after [discussion on Zulip](https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/Lean.204.20extension.20update.20.22Commands.20.26.20Walkthrough.22/near/398244576)
- Change name of `lean4.createMathlibProject` to be easier to understand
> Assorted minor quality improvements

- vscode-lean4/package.json
- vscode-lean4/src/utils/clientProvider.ts
- vscode-lean4/src/utils/leanInstaller.ts
* Ensure that "Restart File" (Ctrl+Shift+X) does not open the extensions menu anymore when in a Lean 4 context
* Make "Toggle Infoview" and "Toggle All Messages" keybindings work when not focusing the editor window
* Ensure that commands displayed in command pallette are independent of focused part of VS Code
* Fix Lean server crashing with bad error message when no default toolchain is set because it was uninstalled in the past
> Assorted minor quality improvements #2

- vscode-lean4/src/utils/clientProvider.ts
When the client would report an error that the project folder is invalid and suggest a parent folder to open, the client wouldn't open the file until the dialog is dismissed. This fixes the issue.
> Still start language client when project folder is invalid

- vscode-lean4/src/utils/leanInstaller.ts
- vscode-lean4/src/utils/projectInfo.ts
Opening the `src` folder in core shows a warning that the opened folder is not a Lean 4 project. This PR adjusts the used heuristic to account for the `src` folder.
> Detect core src directory

- vscode-lean4/src/projectoperations.ts
- vscode-lean4/src/utils/manifest.ts
This PR adjusts the `Project: Update Dependency` command so that it updates the toolchain *after* running `lake update`. This was prompted by the introduction of a post-update hook in leanprover-community/mathlib4#8243 that automatically updates the toolchain.
With the post-update hook and asking to update the toolchain before running `lake update`, a user decision of "Do not update the toolchain" would be ignored for projects downstream of Mathlib, as the post-update hook will update the toolchain regardless of the user choice. Asking to update the toolchain (if it changed) after `lake update` ensures users do not see a misleading dialog.
One caveat is that this means that we will now run `lake update` with the Lean version of the project itself, not the Lean version of its dependency. …
> Update lean toolchain after `lake update`

- vscode-lean4/package-lock.json
- vscode-lean4/package.json
updating `semver` as used version reports vulnerability.
> fix: update semver

- vscode-lean4/src/utils/manifest.ts
"Update Dependency" was broken because of this since [v4.3.0-rc2](https://github.com/leanprover/lean4/releases/tag/v4.3.0-rc2).
> fix: update lake manifest parsing for manifest version 7

- lean4-infoview/package-lock.json
- lean4-infoview/package.json
This is so that the web playground can use the new version.
> Bump @leanprover/infoview

- .eslintrc.js
- lean4-infoview/src/infoview/messages.tsx
- vscode-lean4/src/utils/converters.ts
This is a companion PR to leanprover/lean4#3054.
> Support snippet edits in code actions and workspace edits

- lean4-infoview-api/src/rpcApi.ts
- lean4-infoview/src/infoview/info.tsx
Companion PR to leanprover/lean4#2964.
> feat: optional user widget names

- vscode-lean4/src/leanclient.ts
The disparity between the name of the 'restart file' command and the 'rebuild imports' button has confused people in the past.
> chore: change name of 'rebuild imports' button

- vscode-lean4/src/projectoperations.ts
Some folks were still accidentally updating dependencies, so this PR adds a modal warning to the command.
> feat: display modal warning before updating dependency

- README.md
- lean4-infoview/src/infoview/index.css
- vscode-lean4/package.json
Adds support for user-modifiable colors in the infoview for proof states.
The prior hard-coded values are now used as defaults, so this shouldn't impose a significant cost on users.
> feat: themeable infoview colors

- README.md
- vscode-lean4/package.json
- vscode-lean4/src/config.ts
- vscode-lean4/src/leanclient.ts
Makes it possible to disable substring-based occurrence highlighting and use only Lean's compiler responses.
This is an alternative version of #371 that simplifies the settings interface on the assumption that everyone wants the correct highlights. @mhuisi - this is what we talked about the other day.
> feat: customizable occurrence highlighting

- vscode-lean4/src/projectinit.ts
This PR lifts the restriction that the URLs in the "Download Project" command have to be regular URIs. Instead, we now simply rely on the logic of `git clone`.
Closes #350.
> fix: allow downloading projects with ssh git links

- vscode-lean4/src/abbreviation/rewriter/AbbreviationRewriter.ts
This PR attempts to resolve the race conditions that induce #332 and #373.
#332 was caused by a combination of waiting in the abbreviation provider to mitigate another issue and attempting to update the selection with a state that may be stale.
It has been resolved by removing the waiting call, refactoring the selection update logic to use a less stale state and *only* making the extension move the cursor manually when replacing `$CURSOR` abbreviations, relying on the builtin logic of VS Code to move it when issuing a text editor edit otherwise. 
The former two adjustments only reduce the likelihood of a race condition, whereas the latter should resolve this issue entirely for all input where we are merely appending to an abbreviation: For non-`$CURSOR` abbreviations, we can rely on the …
> fix: mitigate abbreviation race conditions

- lean4-infoview/src/index.tsx
The `LocationsContext` is exported in `infoview/goalLocation.tsx` but not in the `.index.tsx` file. It is sometimes useful to be able to use the `LocationsContext` while writing widgets.
> Export `LocationsContext` in `@leanprover/infoview`

- lean4-infoview/src/infoview/info.tsx
- vscode-lean4/package-lock.json
This wasn't the actual cause of #392 (an off-by-one error in `getInteractiveDiagnostics` on the server side was, c.f. leanprover/lean4#3608), but it's good to fix nonetheless.
> fix: use fullRange diagnostic field when filtering diagnostics

- vscode-lean4/src/projectinit.ts
As suggested in https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/Git.20commit.20after.20project.20creation/near/398713317 by @PatrickMassot.
Also makes the Mathlib project initialization run `lake build` once because I noticed that it would still sometimes issue a "Dependency out of data" warning after initialization.
> feat: add initial commit in new projects

- vscode-lean4/src/projectinit.ts
- vscode-lean4/src/utils/projectInfo.ts
- vscode-lean4/src/utils/setupDiagnostics.ts
The extension will now check whether Git and Lake are installed and issue a helpful message that links to the setup guide when users try to set up projects without these being installed.
> feat: more helpful error when setting up project without lean/git

- vscode-lean4/src/leanclient.ts
- vscode-lean4/src/utils/clientProvider.ts
Client side for leanprover/lean4#3247.
> feat: notification on stale dependency diagnostic

- vscode-lean4/src/abbreviation/AbbreviationHoverProvider.ts
- vscode-lean4/src/abbreviation/AbbreviationProvider.ts
Since we cannot have auto-closing abbreviations (see #417), we might as well improve the discoverability of abbreviations like `\<>` by telling users about it in the abbreviation hover.
> feat: auto-closing abbreviation hover

- lean4-infoview-api/package.json
- lean4-infoview-api/src/infoviewApi.ts
- lean4-infoview/package.json
- lean4-infoview/src/infoview/index.css
- lean4-infoview/src/infoview/info.tsx
- lean4-infoview/src/infoview/main.tsx
- package-lock.json
- vscode-lean4/package.json
- vscode-lean4/src/infoview.ts
- vscode-lean4/src/utils/clientProvider.ts
This PR adds a "Restart File" button to the bottom right of the InfoView and deletes stale dependency notifications entirely.
I've found the latter to be way too noisy, especially now that Lean 4 on master will inform us about stale dependencies as soon as the dependency changes (it's especially noisy when switching branches).
The central issue with the notifications is that they stick around even after you switch away from the file.
Now, after fixing the `fullRange` behavior of the extension, the stale dependency diagnostic will be displayed in "Messages" anywhere in the file. The button in the InfoView should also be sufficiently visible that after reading the message, users know what to do.
This PR also fixes a bug where the InfoView would not correctly display the "imports out of …
> feat: replace stale dep notifs with "restart file" infoview button

- lean4-infoview/src/infoview/goals.tsx
Fixes #398.
This ever so slightly increases the spacing between individual hypotheses, but I don't think that's too bad.
> fix: copyable space between hypotheses

- package-lock.json
- vscode-lean4/package.json
- vscode-lean4/src/abbreviation/config.ts
- vscode-lean4/src/extension.ts
- vscode-lean4/src/taskgutter.ts
- vscode-lean4/src/utils/clientProvider.ts
It turns out that us setting the language ID of files to `lean4` post-hoc after opening the file interferes with semantic highlighting `refresh` requests due to a bug in VS Code (c.f. https://github.com/leanprover/lean4/issues/2977#issuecomment-2029876340).
Since Lean 3 isn't being used much anymore, this PR removes the compatibility with the Lean 3 extension that ensures that we can always run both extensions at the same time. After this PR, there is a potential conflict between the the use of the `.lean` file extension both for the Lean 3 and the Lean 4 language.
To warn users of this potential conflict, a warning is issued when both extensions are enabled, asking users to disable either one of the two.
> chore: replace lean 3 extension compatibility with warning

- README.md
- vscode-lean4/src/docview.ts
- vscode-lean4/src/extension.ts
- vscode-lean4/src/infoview.ts
- vscode-lean4/src/leanclient.ts
- vscode-lean4/src/projectinit.ts
- vscode-lean4/src/projectoperations.ts
- vscode-lean4/src/taskgutter.ts
- vscode-lean4/src/utils/clientProvider.ts
- vscode-lean4/src/utils/configwatchservice.ts
- vscode-lean4/src/utils/exturi.ts
- vscode-lean4/src/utils/fsHelper.ts
- vscode-lean4/src/utils/lake.ts
- vscode-lean4/src/utils/leanInstaller.ts
- vscode-lean4/src/utils/manifest.ts
- vscode-lean4/src/utils/projectInfo.ts
- vscode-lean4/src/utils/setupDiagnostics.ts
- vscode-lean4/test/suite/restarts/restarts.test.ts
- vscode-lean4/test/suite/simple/simple.test.ts
This PR adds support for using multiple lean toolchains in the same workspace folder. It also enables users to use Lean 4 without first having to open a folder.
For nested workspaces, the client uses the outer-most Lean project. This is the correct behavior for projects in `.lake`, but not the correct behavior for actual nested projects. I unfortunately do not see a way to make the latter work because the language client library only supports globs to specify which files should be picked up by a language server, and hence cannot express something like "all Lean files in this directory, except those contained in inner directories with their own lean-toolchain". We could in principle set up middleware for every single notification and request, but this is likely to be overly fragile.
Closes …
> feat: support for multi-toolchain workspaces

- vscode-lean4/src/leanclient.ts
When using a custom `lakePath`, it is helpful to be able to see the error messages if something goes wrong.
> Log errors if something goes wrong with the lake binary

- .git-blame-ignore-revs
Rebasing changed the revision. See #430.
> chore: use correct revision in blame ignore file

- vscode-lean4/src/leanclient.ts
- vscode-lean4/src/projectDiagnostics.ts
- vscode-lean4/src/utils/projectInfo.ts
This fixes an issue where opening the core Lean 4 repository would yield an error and not actually launch the language client because Lake is genuinely missing from stage0.
> fix: only yield 'lake missing' error if `lake --serve` is used

- vscode-lean4/src/utils/fsHelper.ts
- vscode-lean4/src/utils/projectInfo.ts
Some unusual mount-points will report every top-level directory as existing. On such a system, the extension mistakenly thinks a `lean-toolchain` directory is valid.
Similarly, the check for the lean core directory needs to check for some non-directories to avoid a false positive.
> fix: do not consider folders called `lean-toolchain`

- vscode-lean4/src/abbreviation/abbreviations.json
Adds an abbreviation "span" for the Uncode "∙" used in "Mathlib/LinearAlgebra/Span.lean"
See https://leanprover.zulipchat.com/#narrow/stream/113489-new-members/topic/Show.20the.20basis.20vectors.20of.20R.5En.20sum.20to.20R.5En/near/439392547
> add span abbreviation

- vscode-lean4/src/globalDiagnostics.ts
- vscode-lean4/src/projectinit.ts
Since `elan self update` was broken in Elan 3.1.0, we can't actually update `elan` that way. Instead, we now re-run the installation script for this version.
Also removes the `elan self update` call when attempting to create a project.
> fix: special update handling for elan 3.1.0

- vscode-lean4/src/leanclient.ts
- vscode-lean4/src/utils/clientProvider.ts
- vscode-lean4/src/utils/converters.ts
- vscode-lean4/src/utils/docInfo.ts
This PR fixes an issue reported at https://leanprover.zulipchat.com/#narrow/stream/113489-new-members/topic/VSCODE.20outline.20mode.20not.20working.20in.20imports/near/442000461 that caused the VS Code outline and other features that rely on document symbols to not display anything when initially opening the document.
The synopsis is as follows (in case anyone stumbles upon related issues in the future):
1. By default, VS Code triggers `onDidOpenTextDocument` when hovering over an identifier while holding `Ctrl`, which in turn makes the language client library emit a `didOpen` notification to the language server (closely followed by `didClose` when moving the mouse away from the identifier). 
2. This puts unnecessary pressure on the language server since it starts elaborating the file, …
> fix: broken document symbols

- vscode-lean4/src/leanclient.ts
Reported at https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/.E2.9C.94.20Warning.20in.20project.20version/near/442775409.
I have a hunch that this is because #460 switched to using the set of open documents tracked by the language client. I already noticed a potential bug in the language client library in that PR, but thought that this bug would not affect us. Perhaps it does. Typically, I prefer using state that is already there to avoid introducing race conditions, but it looks like that may not be possible here.
> fix: don't use language client tracking of open documents

- package-lock.json
- vscode-lean4/src/utils/manifest.ts
Lake changed its Manifest version format to semantic versioning in https://github.com/leanprover/lean4/pull/4083. This PR ensures that we can still parse the new format.
> feat: support for new manifest version format

- vscode-lean4/manual/manual.md
- vscode-lean4/package.json
- vscode-lean4/src/loogleview.ts
`Ctrl+Shift+L` conflicts with the shortcut of the existing Loogle extension, so we change it to the `Ctrl+K Ctrl+S` chord.
> chore: loogleview shortcut and lower max-width

- vscode-lean4/package.json
- vscode-lean4/src/abbreviation/AbbreviationRewriterFeature.ts
- vscode-lean4/src/abbreviation/VSCodeAbbreviationRewriter.ts
This fixes an issue introduced in the abbreviation refactor of #469 that would sometimes cause the extension to not activate properly because a command was attempted to be registered multiple times. It also fixes another bug where `Tab` completion did not work correctly in non-Lean 4 files.
Fixes #475.
> fix: 'lean4.input.convert already registered' error

- vscode-lean4/src/abbreviation/AbbreviationFeature.ts
- vscode-lean4/src/abbreviation/AbbreviationRewriterFeature.ts
- vscode-lean4/src/abbreviation/VSCodeAbbreviationRewriter.ts
- vscode-lean4/src/extension.ts
- vscode-lean4/src/utils/internalErrors.ts
In #469, I refactored the abbreviation provider to maintain one abbreviation rewriter per visible text editor. The idea was that it would be nice if the abbreviation state was maintained when switching between visible text editors.
It turns out that this is way too fiddly to get right:
- Since `TextEditor`s have no ID, it relies on the fact that `TextEditor` references are stable. I'm not sure if this is actually true, and I don't want to debug issues that are caused by this assumption being violated.
- The abbreviation rewriters for two text editors for the same text can trample over one another.
- The benefit isn't huge. We already always replace abbreviations when the selection is moved away from the abbreviation, so why shouldn't this also be the case when moving the cursor across …
> fix: revert to using one abbreviation rewriter for active editor

- vscode-lean4/loogleview/index.ts
Looks like setting the user agent in the web view doesn't really work, so we now set a separate HTTP header to tell Loogle about us. cc @nomeata
> feat: set x-loogle-client header for loogle requests

- vscode-lean4/src/diagnostics/fullDiagnostics.ts
- vscode-lean4/src/diagnostics/setupDiagnoser.ts
- vscode-lean4/src/diagnostics/setupDiagnostics.ts
- vscode-lean4/src/extension.ts
This helps us debug old VS Code extension versions and warns users if their VS Code version will not clear an extension VS Code version requirement.
> feat: vs code and vs code extension version diagnostics

- vscode-lean4/src/diagnostics/fullDiagnostics.ts
- vscode-lean4/src/extension.ts
- vscode-lean4/src/utils/clientProvider.ts
- vscode-lean4/src/utils/configwatchservice.ts
- vscode-lean4/src/utils/internalErrors.ts
- vscode-lean4/src/utils/projectInfo.ts
This PR fixes two issues reported at https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/VS.20Code.20error.20too.20big.20to.20remove/near/447340051:
- When displaying an activation error, the popup can get too large, rendering VS Code unusable. We now only display the error message without the stack trace, but copy it when using the "Copy Error to Clipboard" button.
- Activating the VS Code extension would sometimes crash when VS Code attempts to open a document with a file URI that does not exist on the file system anymore. This happens when a file has unsaved changes, VS Code is closed, the file is deleted and VS Code is re-opened.
> fix: crash when vs code opens files that do not exist

- vscode-lean4/src/abbreviation/AbbreviationRewriterFeature.ts
- vscode-lean4/src/abbreviation/VSCodeAbbreviationRewriter.ts
This issue fixes a noisy and persistent error that was reported in #489. It may also have caused a leak in abbreviation rewriters over time.
> fix: abbreviation rewriter disposal race condition

- README.md
- vscode-lean4/README.md
The VS Code marketplace always attempts to resolve these URLs that are relative to the README in the vscode-lean4 folder in a manner that is relative to the repository, so now we just use the image links directly. That's what the marketplace replaces them as anyways.
> doc: use image urls for everything

- lean4-infoview/src/infoview/collapsing.tsx
- lean4-infoview/src/infoview/goalLocation.tsx
- lean4-infoview/src/infoview/goals.tsx
- lean4-infoview/src/infoview/info.tsx
- lean4-infoview/src/infoview/messages.tsx
- lean4-infoview/src/infoview/tooltips.tsx
- lean4-infoview/src/infoview/traceExplorer.tsx
> fix: filter menu button collapsing goal state

- vscode-lean4/manual/manual.md
Based on leanprover/lean4#5015, use emoji-variant selector for ❌️ across the Lean universe.
> chore: use emoji-variant for ❌️

- vscode-lean4/package.json
This should hopefully make it easier to find the Lean 4 extension when searching for "Lean" (due to the way that the VS Code fuzzy search works). This PR also adds a "lean4" keyword so that the extension can still be found with the old identifier.
> chore: change extension display name

- .github/workflows/on-push.yml
Per https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/.
> chore: update actions/upload-artifact

- lean4-infoview/package.json
checking https://www.npmjs.com/package/@leanprover/infoview?activeTab=code,
export index.production.min.js rather than export index.development.js for only index.production.min.js in the dist
> export index.production.min.js

- lean4-infoview/src/infoview/info.tsx
While developing some widgets today I noticed that their state is no longer persisted when the cursor moves. The resulting re-mounting/reinitialization can be bad for performance, is jittery (see recordings), and makes it impossible for widgets to animate between adjacent states.
Persistence was broken in #500 with the addition of a `key` that resets the entire `GoalInfoDisplay` component. This PR removes the key and reintroduces a state-clearing operation which is needed for correctness, but follows React docs so that there should hopefully not be any degradation in performance (I did not measure this, however). Note that setting state during rendering does technically result in a re-render, but it's a cheap one: the JSX that was returned in the first pass is never mounted or rendered. …
> fix: widget persistence

- vscode-lean4/manual/manual.md
> doc: list default settings and how to override them in the manual

- vscode-lean4/src/diagnostics/fullDiagnostics.ts
- vscode-lean4/src/diagnostics/setupDiagnoser.ts
- vscode-lean4/src/diagnostics/setupDiagnostics.ts
- vscode-lean4/src/extension.ts
- vscode-lean4/src/projectinit.ts
- vscode-lean4/src/projectoperations.ts
- vscode-lean4/src/utils/batch.ts
- vscode-lean4/src/utils/clientProvider.ts
- vscode-lean4/src/utils/elan.ts
- vscode-lean4/src/utils/lake.ts
This PR improves two things about the way we report progress:
- Instead of attempting to badly approximate an accurate progress bar that gets stuck whenever the output of a command doesn't change, we now use VS Code's "infinite" progress bars everywhere that clearly show that an operation is actively running in the background.
- Every progress bar is prefixed with a context to make it clear which operation caused the operation. For example, when creating a new mathlib project, all external commands executed while creating the project are prefixed with "[Create Mathlib Project]".
Closes #457. IMO, our dialog UX still isn't perfect, but there doesn't seem to be a good way to improve these things short of implementing our own webviews for every command.
> feat: better progress ux

- vscode-lean4/manual/manual.md
- vscode-lean4/package.json
- vscode-lean4/src/leanclient.ts
- vscode-lean4/src/projectoperations.ts
- vscode-lean4/src/utils/clientProvider.ts
Also fixes some potential bugs caused by exceptions, turns the server startup progress bar into an infinite one and renames the command to make it more clear what it does.
> feat: restart file button in 'fetch cache for focused file' command

- lean4-infoview/package.json
- lean4-infoview/src/infoview/main.tsx
- package-lock.json
- vscode-lean4/.vscodeignore
- vscode-lean4/abbreviationview/index.ts
- vscode-lean4/loogleview/index.ts
- vscode-lean4/loogleview/static/index.css
- vscode-lean4/loogleview/static/index.html
- vscode-lean4/moogleview/index.ts
- vscode-lean4/moogleview/static/index.css
- vscode-lean4/moogleview/static/index.html
- vscode-lean4/package.json
- vscode-lean4/src/abbreviationview.ts
- vscode-lean4/src/loogleview.ts
- vscode-lean4/src/moogleview.ts
- vscode-lean4/webpack.config.js
[`@vscode/webview-ui-toolkit` is being deprecated in January](https://github.com/microsoft/vscode-webview-ui-toolkit/issues/561). This PR replaces the UI components from `@vscode/webview-ui-toolkit` with components from `@vscode-elements/elements`.
> chore: replace webview-ui-toolkit

- vscode-lean4/webview/index.ts
This PR allows the Infoview to be detached into a separate window (e.g. for use on a second monitor).
Issue originally reported at https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/VSCode.20floating.20infoview/near/437975918.
> feat: detachable infoview

- lean4-infoview/package.json
- lean4-infoview/src/infoview/info.tsx
- package-lock.json
> feat: add subtle spinner while infoview is loading

- vscode-lean4/src/diagnostics/fullDiagnostics.ts
- vscode-lean4/src/diagnostics/setupDiagnostics.ts
- vscode-lean4/src/diagnostics/setupNotifs.ts
- vscode-lean4/src/extension.ts
- vscode-lean4/src/infoview.ts
- vscode-lean4/src/leanclient.ts
- vscode-lean4/src/projectinit.ts
- vscode-lean4/src/projectoperations.ts
- vscode-lean4/src/utils/batch.ts
- vscode-lean4/src/utils/clientProvider.ts
- vscode-lean4/src/utils/events.ts
- vscode-lean4/src/utils/internalErrors.ts
- vscode-lean4/src/utils/leanEditorProvider.ts
- vscode-lean4/src/utils/leanInstaller.ts
- vscode-lean4/src/utils/notifs.ts
- vscode-lean4/test/suite/bootstrap/bootstrap.test.ts
- vscode-lean4/test/suite/multi/multi.test.ts
- vscode-lean4/test/suite/restarts/restarts.test.ts
- vscode-lean4/test/suite/simple/simple.test.ts
- vscode-lean4/test/suite/toolchains/toolchain.test.ts
This PR changes the notifications for extension startup errors to a new "sticky" notification mechanism.
Before this PR, when one of the precondition checks of the extension failed (e.g. because Lean was not installed), we would issue a small non-modal notification in the bottom right and then rely on users to figure out that after fixing their setup, they need to open a new Lean document to restart the check. If users closed this notification, there would also be no further indication for why the extension is not activating.
This is quite unintuitive, so we now instead issue a modal notification when the error first occurs and then a sticky notification that re-appears whenever a new Lean text editor is made visible. Clicking the retry button on this notification will re-try the check. …
> feat: sticky notifications for extension startup errors

- vscode-lean4/src/utils/clientProvider.ts
This adds the disposable returned by the event registrations to `this.subscriptions` so that calling `dispose` will get rid of all event listeners.
This will help with lean4web, but is probably generally the right thing to do here.
> fix: register event listeners for proper disposal of client provider

- vscode-lean4/package.json
- vscode-lean4/src/extension.ts
- vscode-lean4/src/utils/notifs.ts
- vscode-lean4/src/utils/viewColumn.ts
- Fixes a bug where InfoView would not appear in locked tab group after restarting VS Code
- Adds a command to the forall menu for re-displaying a sticky setup error in case it was closed by accident and users have no clue how to re-open it (by selecting a new Lean tab)
> feat: refinements for 185

- vscode-lean4/src/leanclient.ts
- vscode-lean4/src/projectinit.ts
- vscode-lean4/src/utils/fsHelper.ts
- vscode-lean4/src/utils/projectInfo.ts
- vscode-lean4/test/suite/utils/helpers.ts
This PR replaces
```
import path = require('path')
```
by
```
import path from 'path'
```
in a couple of files.
> refactor: replace require-style imports

- lean4-infoview/package.json
- lean4-infoview/rollup.config.js
- lean4-infoview/src/infoview/userWidget.tsx
- package-lock.json
The diff on `userWidget.tsx` explains the purpose of this PR.
> feat: support importing widget modules by hash

- vscode-lean4/manual/manual.md
- vscode-lean4/media/guide-help.md
- vscode-lean4/media/guide-installDeps-mac.md
- vscode-lean4/media/guide-setupProject.md
Adds a note about disabling automatic hovers to the manual and notes about antivirus software, adding `brew` to the PATH and network drives or cloud storage to the setup guide.
Closes #533.
> doc: minor adjustments to manual and setup guide

- vscode-lean4/media/guide-installElan-unix.md
- vscode-lean4/media/guide-installElan-windows.md
- vscode-lean4/src/utils/leanInstaller.ts
With Elan 4.0.0, installing Elan doesn't actually install a toolchain anymore. Only when creating or opening a project it will install a toolchain. This PR adjusts the setup guide and the Elan installation prompt to reflect that.
> fix: do not suggest that installing elan also installs lean

- lean4-unicode-input-component/README.md
Came across this while I tried to use the input. Took me a while to figure out why it wasn't behaving like on https://loogle.lean-lang.org/, so I think the fix should be documented.
> chore: document white-space fix for firefox

- lean4-unicode-input-component/package.json
- lean4-unicode-input-component/src/index.ts
I tried to use this component, but it prevents accessibility because it prevents default for all `tab` clicks.
> fix: only prevent default for `tab` if it replaces something

- lean4-unicode-input-component/package.json
- lean4-unicode-input/package.json
- package-lock.json
- vscode-lean4/package.json
The 0.1.1 versions of both packages lacked a `dist` directory. Thanks to @joneugster for noticing.
> chore: bump unicode input versions again

- vscode-lean4/src/taskgutter.ts
I somehow reverted this by accident during testing. `1ch` of padding feels much more consistent for the unsolved goal symbol.
> fix: use 1ch unsolved goal padding instead of 1em

- vscode-lean4/package.json
The language client library has a very convenient setting for tracing language server messages on the client-side, but I'm getting tired of having to edit the `settings.json` to use it. This PR exposes the client-side logging setting in the vscode-lean4 config.
> feat: expose client-side language server logging in config

- vscode-lean4/package.json
- vscode-lean4/src/config.ts
- vscode-lean4/src/taskgutter.ts
This PR makes the edit delay for the "unsolved goal" decoration adjustable for testing purposes, reduces it to 750ms and fixes a bug that caused the decoration to sometimes be displayed in the wrong location for a moment.
> feat: adjust edit delay and make it configurable

- lean4-unicode-input/src/abbreviations.json
These symbols are in use within combinatorial game theory, and are used in the [CGT repo](https://github.com/vihdzp/combinatorial-games).
> feat: add `\tiny` and `\miny` for `⧾` and `⧿`

- vscode-lean4/package.json
- vscode-lean4/src/config.ts
This PR allows theme colors in the color settings for the 'unsolved goals' decoration and changes the default color of the 'unsolved goals' decoration to `editorInfo.foreground`.
> feat: theme colors in 'unsolved goals' decoration

- vscode-lean4/src/extension.ts
- vscode-lean4/src/utils/uriHandlerService.ts
I’m not certain whether this is the best place to add a new `registerUriHandler`. However, it's a hook for the URI `vscode://leanprover.lean4/setup-guide`, which will open the setup guide. This is useful for future documentation in the web, especially when detailing the installation process.
> feat: add uri handler for the setup-guide

- vscode-lean4/test/suite/bootstrap/bootstrap.test.ts
- vscode-lean4/test/suite/info/info.test.ts
- vscode-lean4/test/suite/multi/multi.test.ts
- vscode-lean4/test/suite/restarts/restarts.test.ts
- vscode-lean4/test/suite/simple/simple.test.ts
- vscode-lean4/test/suite/toolchains/toolchain.test.ts
- vscode-lean4/test/suite/utils/helpers.ts
This PR adjusts tests that check the contents of 'All Messages' to check the content of 'Messages' instead, which (when initializing the InfoView for the first time) is sometimes subject to a race condition that makes it not display any messages. This is a known, albeit minor, issue.
> test: make tests more stable

- vscode-lean4/package.json
- vscode-lean4/src/diagnostics/setupDiagnostics.ts
- vscode-lean4/src/leanclient.ts
- vscode-lean4/src/utils/clientProvider.ts
- vscode-lean4/src/utils/exturi.ts
- vscode-lean4/src/utils/internalErrors.ts
- vscode-lean4/src/utils/projectInfo.ts
This PR makes the following adjustments:
- Fix a potential bug where nested workspace folders could lead to nested language servers (i.e. in core)
- Improve error reporting for nested language servers
- Improve error reporting for the 'Restart File' command
> feat: errors for nested projects

- vscode-lean4/package.json
This PR prevents users from accidentally editing dependencies in `.lake` and `.elan` when jumping to them, e.g. using go-to-definition.
> feat: make lean files in `.lake` and `.elan` read-only

- vscode-lean4/src/utils/internalErrors.ts
Every so often, users decide that they want to get (what they believe to be) the "full" Lean experience in VS Code and install every single Lean-related extension from the VS Code marketplace. While well-intentioned, since the marketplace also contains forks of our extension, this then leads to an internal activation error when VS Code's `commands.registerCommand` API throws an exception for trying to register duplicate commands. 
This PR improves the error message that is displayed in this case to hint at the cause so that users are more likely to be able to fix it themselves without requiring assistance.
> feat: improve activation error when forked extension is installed

- lean4-infoview-api/package.json
- lean4-infoview-api/src/infoviewApi.ts
- lean4-infoview/package.json
- lean4-infoview/src/infoview/collapsing.tsx
- lean4-infoview/src/infoview/goals.tsx
- lean4-infoview/src/infoview/info.tsx
- lean4-infoview/src/infoview/messages.tsx
- lean4-infoview/src/infoview/traceExplorer.tsx
- package-lock.json
- vscode-lean4/package.json
- vscode-lean4/src/config.ts
- vscode-lean4/src/infoview.ts
- vscode-lean4/test/suite/info/info.test.ts
- vscode-lean4/test/suite/simple/simple.test.ts
This PR revamps the option and action UX of the InfoView. This work is motivated by several reports from users that they never knew that certain InfoView functionality existed, and intends to make these features more discoverable. Closes #592.
Specifically, the following adjustments are made:
- The filter menu was difficult to discover and users had trouble finding the 'reverse tactic state' functionality. To improve this, all goal state settings have been moved into a single 'Settings' menu that uses a standard cog icon, which should hopefully be much more recognizable. 
- All goal state settings are now also available in the 'Settings' submenu of the InfoView context menu.
- The 'Unselect All' context menu entry is now only visible when there is something to be unselected, as is the …
> feat: revamp infoview options and actions

- lean4-infoview/package.json
- lean4-infoview/src/infoview/tooltips.tsx
- package-lock.json
- vscode-lean4/package.json
This PR ensures that the tooltip hover popup doesn't trigger while the primary mouse button is being held to prevent it from popping up while user are selecting text.
> fix: don't display popups during mouse selection

- vscode-lean4/src/diagnostics/setupDiagnoser.ts
- vscode-lean4/src/diagnostics/setupDiagnostics.ts
This PR fixes the fallout of a small ticking time bomb that exploded in v4.21.0-rc1.
Lake reports its version strings as follows, where `77cfc4d` is the commit ID of the corresponding release:
```
[mhuisi@fedora ~]$ lake --version
Lake version 5.0.0-77cfc4d (Lean version 4.20.0)
```
In v4.21.0-rc1, the commit ID is `0168680`, so Lake reports the following version string:
```
[mhuisi@fedora ~]$ lake --version
Lake version 5.0.0-0168680 (Lean version 4.21.0-rc1)
```
Unfortunately, `5.0.0-0168680` is *not* a [valid semantic version](https://semver.org/), since it both contains a 0 at the start and only numbers. This is fairly rare, but it now happened on v4.21.0-rc1 for the first time.
The VS Code extension parses this version as part of its precondition checks, which now fails because the …
> fix: workaround for invalid lake version in v4.21.0-rc1

- vscode-lean4/syntaxes/lean4.json
`#stringBlock` is a block in the lean 3 / lean 4 syntax file, and it was added in 48ad018 on 2020-06-23, when people were developing in the legacy vscode-lean repo.
Later, `#stringBlock` was removed in ca65431 on 2021-01-18 when migrating from lean 3 to lean 4.
Somehow, the `include` line was forgotten. This PR now removes the line.
In fact, VS Code’s parser (vscode-textmate) will tolerate missing includes, so the original syntax works.
(You could verify it by amending `~/.vscode/extensions/leanprover.lean4-0.0.207/syntaxes/lean4.json` and reloading the VS Code window.)
However, including the inexistent `#stringBlock` will cause problems for a downstream project. 
If you are concerned about the details, please refer to https://github.com/sharkdp/bat/issues/3286.
> chore: remove the redundant `include: #stringBlock` in lean4 syntax

- vscode-lean4/src/projectinit.ts
- vscode-lean4/src/projectoperations.ts
- vscode-lean4/src/utils/batch.ts
- vscode-lean4/src/utils/lake.ts
This PR ensures that the VS Code extension always reports the error that occurred when `lake exe cache get` fails in Mathlib or in a project downstream of Mathlib. Previously, this was only the case for project creation commands.
> feat: improve `lake exe cache get` error reporting

- vscode-lean4/src/diagnostics/setupDiagnoser.ts
Elan 4.0.0 has been out for a while now, so we now issue a warning if the Elan version is older than that.
> chore: bump recommended elan version to 4.0.0

- lean4-infoview-api/src/infoviewApi.ts
- lean4-infoview/src/infoview/goals.tsx
- lean4-infoview/src/infoview/messages.tsx
- vscode-lean4/package.json
- vscode-lean4/src/infoview.ts
This PR re-adds the copy state/message to clipboard functionality after it was removed in #606. The functionality is available from the context menu (as the other "edit" webview actions are), not from an icon button.
> feat: re-add copy state/message functionality

- vscode-lean4/package.json
This PR increases the delay until VS Code emits an auto-completion request from 10ms to 200ms. A delay of 10ms means that VS Code will immediately emit a completion request for the first character for most users, even if they continue typing, which tends to be very expensive if e.g. `import Mathlib` is at the top of the file.
> feat: increase delay until completion requests are emitted

- lean4-infoview-api/package.json
- lean4-infoview-api/src/infoviewApi.ts
- lean4-infoview-api/src/rpcApi.ts
- lean4-infoview/package.json
- lean4-infoview/src/index.tsx
- lean4-infoview/src/infoview/contexts.ts
- lean4-infoview/src/infoview/index.css
- lean4-infoview/src/infoview/interactiveCode.tsx
- lean4-infoview/src/infoview/main.tsx
- lean4-infoview/src/infoview/messages.tsx
- lean4-infoview/src/infoview/traceExplorer.tsx
- package-lock.json
- vscode-lean4/package.json
- vscode-lean4/src/leanclient.ts
- vscode-lean4/src/utils/converters.ts
This PR implements the client-side for a new trace search mechanism in the InfoView.
Demo:
> feat: client-side for trace search

- lean4-unicode-input/src/abbreviations.json
Currently `\ma` turns into `♂`. This PR changes it to much more common `↦` (`\mapsto`).
Zulip discussion: [#mathlib4 > Switch to ↦ (\mapsto) globally @ 💬](https://leanprover.zulipchat.com/#narrow/channel/287929-mathlib4/topic/Switch.20to.20.E2.86.A6.20.28.5Cmapsto.29.20globally/near/535319694)
> feat: add shortcut for `↦`

- lean4-infoview/src/infoview/interactiveCode.tsx
> fix: don't override selected text in infoview

- lean4-infoview/src/infoview/index.css
- lean4-infoview/src/infoview/info.tsx
- lean4-infoview/src/infoview/messages.tsx
- lean4-infoview/src/infoview/util.ts
This PR distinguishes the message counters of "Messages" and "All Messages" in the InfoView by severity.
Closes #574.
> feat: distinguish message tally by severity
